version: '3'
services:
    selenium-chrome:
        image: selenium/standalone-chrome:3.12.0
        volumes:
            - /dev/shm:/dev/shm
    robot:
        build: tests
        environment:
            - SELENIUM_HOST=selenium-chrome
            - SELENIUM_PORT=4444
            - APPLICATION_HOST=web-application
            - APPLICATION_PORT=8080
        volumes:
            - ./tests/results:/results:rw
        depends_on:
            - web-application
            - selenium-chrome
