version: '3'
services:
    redis:
        image: redis
    web-application:
        build: web-application
        environment:
            - PORT=8080
            - REDIS_HOST=redis
        ports:
            - 8080:8080
        depends_on:
            - redis
